version: '3.8'

services:
  talk-tracker:
    build: .
    container_name: talk-tracker-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=your-super-secure-session-secret-change-this
      # Email configuration (uncomment and configure for production)
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_PORT=587
      # - SMTP_USER=your-email@gmail.com
      # - SMTP_PASS=your-app-password
    volumes:
      # Persistent data storage
      - talk_tracker_data:/app/data
      # Optional: bind mount for development
      # - ./data:/app/data
    restart: unless-stopped
    networks:
      - talk_tracker_network
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: talk-tracker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL certificates (uncomment for HTTPS)
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - talk-tracker
    restart: unless-stopped
    networks:
      - talk_tracker_network
    profiles:
      - production

volumes:
  talk_tracker_data:
    driver: local

networks:
  talk_tracker_network:
    driver: bridge